@echo off
echo Starting SEIT Frontend...
echo Checking for node_modules...
if not exist "node_modules" (
    echo Installing dependencies...
    pnpm install
)
echo Starting development server...
pnpm dev
pause
